load("//third_party:workspace.bzl", llvm = "repo")

# Load the raw llvm-project.  llvm does not have build rules set up by default,
# but provides a script for setting up build rules via overlays.
llvm("llvm-raw")

load("//third_party:setup.bzl", "llvm_setup")
llvm_setup(name = "llvm-project")

# tensorflow
local_repository(
    name = "org_tensorflow",
    path = "./third_party/tensorflow",
)

load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")
tf_workspace3()

load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")
tf_workspace2()

load("@org_tensorflow//tensorflow:workspace1.bzl", "tf_workspace1")
tf_workspace1()

load("@org_tensorflow//tensorflow:workspace0.bzl", "tf_workspace0")
tf_workspace0()
