load("//third_party:workspace.bzl", llvm = "repo")

# Load the raw llvm-project.  llvm does not have build rules set up by default,
# but provides a script for setting up build rules via overlays.
llvm("llvm-raw")

load("//third_party:setup.bzl", "llvm_setup")
llvm_setup(name = "llvm-project")